#!/bin/bash
echo "Starting Lightning Node!"
source /usr/src/app/env/bin/activate

for i in `seq 1 10`;
do
        echo $i;
        sleep 0.25;
	python3 --version
done  
# echo 


# download Bitcoin Core binary and also check out commit on GitHub
# git clone --branch $BITCOIND_VERSION git@github.com:bitcoin/bitcoin.git --depth 1

wget https://bitcoincore.org/bin/bitcoin-core-$BITCOIND_VERSION/bitcoin-$BITCOIND_VERSION-arm-linux-gnueabihf.tar.gz
wget https://bitcoincore.org/bin/bitcoin-core-$BITCOIND_VERSION/SHA256SUMS.asc
wget https://bitcoin.org/laanwj-releases.asc

tar -xvf bitcoin-$BITCOIND_VERSION-arm-linux-gnueabihf.tar.gz
install -m 0755 -o root -g root -t /usr/local/bin bitcoin-$BITCOIND_VERSION/bin/*

bitcoind --version

# download LND binary and also check out commit on GitHub
# git clone --branch $LND_VERSION git@github.com:lightningnetwork/lnd.git --depth 1
tar -xzf lnd-linux-armv7-$LND_VERSION.tar.gz
wget https://github.com/lightningnetwork/lnd/releases/tag/v0.5.2-beta
wget https://github.com/lightningnetwork/lnd/releases/download/$LND_VERSION/lnd-linux-armv7-$LND_VERSION.tar.gz
wget https://github.com/lightningnetwork/lnd/releases/download/$LND_VERSION/manifest-$LND_VERSION.txt
wget https://github.com/lightningnetwork/lnd/releases/download/$LND_VERSION/manifest-$LND_VERSION.txt.sig
wget https://keybase.io/roasbeef/pgp_keys.asc

tar -xvf lnd-linux-armv7-$LND_VERSION.tar.gz
install -m 0755 -o root -g root -t /usr/local/bin lnd-linux-armv7-$LND_VERSION/*

# Mount Solid State drive
mkdir /root/bitcoin_data/
echo "UUID=e265cce8-27f4-4b1a-9af0-5034b140457b  /root/bitcoin_data/      ext4	    defaults,errors=remount-ro 0       1" >> /etc/fstab
# mount -a
mount -t ext4 /dev/sda$DATA_PARTITION_NUM /root/bitcoin_data/
# Link data on drive to standard location used by bitcoind and lnd.
# Notice no trailing slash on source!
ln -s /root/bitcoin_data/bitcoin /root/.bitcoin
ln -s /root/bitcoin_data/lnd /root/.lnd

# Enable service files copied in Dockerfiles
bitcoind
echo "Waiting 30 seconds before starting LND"
sleep 30
echo "Starting LND!"
nohup lnd > /usr/src/app/foo.out 2> /usr/src/app/foo.err < /dev/null &

echo "Completed download, installation, and autostart setup of LND and Bitcoind!"

python3 -m http.server 80 &

while [[ true ]]; do
	echo "Node is Up!!";
	sleep 5;
done
